module.exports = [
  './src/gulp/tasks/sass',
  './src/gulp/tasks/purgecss',
  './src/gulp/tasks/scripts',
  './src/gulp/tasks/copy',
  './src/gulp/tasks/clean',
  './src/gulp/tasks/allimg',
  './src/gulp/tasks/html',
  './src/gulp/tasks/nunjucks',
  './src/gulp/tasks/images',
  './src/gulp/tasks/serve',
  './src/gulp/tasks/webp',
  './src/gulp/tasks/svg',
  './src/gulp/tasks/spritepng',
  './src/gulp/tasks/build',
];
